import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outFile = resolve(root, 'lib/client.js')
const source = await readFile(resolve(root, 'src/client.js'), 'utf8')
const code = source
  .replace("import { createElement } from 'react'", "const { createElement } = require('react')")
  .replace("import { createSnapshotStore } from '@deepseek-ai/dsh-client-store'", "const { createSnapshotStore } = require('@deepseek-ai/dsh-client-store')")
  .replace('export const inject =', 'exports.inject =')
  .replace('export function apply(', 'exports.apply = function apply(')
if (/(?:^|\n)\s*(?:import|export)\s/.test(code)) throw new Error('src/client.js contains an unsupported module declaration')
const artifact = `// Generated by scripts/build-client.mjs. Do not edit directly.\nwindow.__ModuleLoader__.load({ id: 'dsh-ollama-control', factory: (require) => {\nvar module = { exports: {} }; var exports = module.exports;\n${code}\nreturn module.exports;\n} });\n`
await mkdir(dirname(outFile), { recursive: true })
await writeFile(outFile, artifact)
